apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwb-app
  labels:
    app: uwb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwb-app
  template:
    metadata:
      labels:
        app: uwb-app
    spec:
      containers:
      - name: uwb-app
        image: REPOSITORY_URL/uwb-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: regcred