apiVersion: v1
kind: Service
metadata:
  name: uwb-app-service
  labels:
    app: uwb-app
spec:
  type: NodePort
  selector:
    app: uwb-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080